#!/usr/bin/env -S deno run -A --watch
import { serveFile } from "jsr:@std/http/file-server";

const mult = (p:number[]) => [matrix[0]*p[0]+matrix[1]*p[1]+matrix[4], matrix[2]*p[0]+matrix[3]*p[1]+matrix[5]];
const render = (vals:number[]):string => vals.map(x=>shape(x).map((y,n)=>(n?'':'M')+(y.length?`${mult(y)[0]} ${mult(y)[1]}`:'Z'+(n+1==shape().length?'':'M'))).join(' ')).join(';');
const s = (v:number,a:number,b:number) => v < a ? 0 : v > b ? 1 : (v-a)/(b-a);
const size = [650,50];
const F = 36+10;
const FS = [12,F];
const animation = [
    // Loading
    //-3/3, -2/3, -1/3, -0/3,
    // Titlecard
    ...Array(FS[1]-FS[0]).fill(0).map((_,n) => (n+FS[0])/F),
];
console.log(animation);

/** Matrix Tranformation (x,y) => (ax+by+e, cx+dy+f) */
const matrix = [8.25,2,0,-8.25,size[0]/2,size[1]/2];//8,74];
/** Shape Rendering
  * - `loading`
  *   - `-1` to `0` seconds
  *   - `-12` to `0 frames
  *   - `-3` to `0` steps
  * - `title`
  *   - `0` to `1` seconds
  *   - `0` to `34` frames
  */
const shape = (t:number=0) => {
    const u = (S:number, E:number) => (E-S)*s(t, S/(S<0?12:F), E/(E<0?12:F));
    const S:{[letter:string]:number[][]} = {
        L: [
            // BL
            [3-u(-12,-4),-3],
            // TL
            [3-u(-12,-4),-1+u(-4,0)],
            // TR
            [3-1.5*u(-8,-4),-1+u(-4,0)],
            // ML
            [3-1.5*u(-8,-4),-1],
            [3-u(-4,-2),-1],
            // TO INNER TOP RIGHT
            [3-u(-4,-2),1-u(-6,-4)],
            // TO BOTTOM OF TOP
            [-1-u(-4,-2)+u(-12,-8),1-u(-6,-4)],
            [-1-u(-4,-2)+u(-12,-8),3-u(-8,-4)],
            [5-u(-4,0),3-u(-8,-4)],
            // MR
            [5-u(-4,0),-1],
            // BR
            [5-u(-4,0),-3],
            [],
        ],
        // 6, 4
        A: [
            [2,-3],
            [2,-3+u(2,8)],
            [2+u(0,2)+u(8,12),-3+u(2,8)],
            [2+u(0,2)+u(8,12),-3+u(4,8)-u(12,16)],
            [2+u(0,2)+u(10,12),-3+u(4,8)-u(12,16)],
            [2+u(0,2)+u(10,12),-3+u(4,8)-u(13,16)],
            [2+u(0,2)+u(10,12)-u(16,18),-3+u(4,8)-u(13,16)],
            [2+u(0,2)+u(10,12)-u(16,18),-3+u(4,8)-u(15,16)],
            [2+u(0,2)+u(10,12),-3+u(4,8)-u(15,16)],
            [2+u(0,2)+u(10,12),-3+u(4,8)],
            [2+u(0,2),-3+u(4,8)],
            [2+u(0,2),-3],
            [],
        ],
        S: [
            [9,3-u(10,12)-0.8*u(18,20)], //  [9,-0.6],
            [9,3],              //  [9,3],
            [9+u(12,18),3],     //  [15,3],
            [9+u(12,18),3-u(10,12)],     //  [15,1],
            [9+u(12,14),3-u(10,12)],     //  [11,1],
            [9+u(12,14),3-u(10,12)-0.2*u(18,20)],    // [11,0.6],
            [9+u(12,14)+u(20,24),3-u(10,12)-0.2*u(18,20)],    // [15,0.6],
            [9+u(12,14)+u(20,24),3-u(10,12)-0.8*u(18,20)-1.2*u(24,26)],    // [15,-3],
            [9+u(12,14)+u(20,22)-u(26,30),3-u(10,12)-0.8*u(18,20)-1.2*u(24,26)], // [9,-3],
            [9+u(12,14)+u(20,22)-u(26,30),3-u(10,12)-0.8*u(18,20)-0.4*u(24,26)], /*[9,-1],*/
            [9+u(12,14)+u(20,22),3-u(10,12)-0.8*u(18,20)-0.4*u(24,26)], //[13,-1],
            [9+u(12,14)+u(20,22),3-u(10,12)-0.8*u(18,20)], // [13,-0.6],
            [],
        ],
        O: [
            [16,3-u(16,18)],
            [16,3],
            [16+u(18,24),3],//[22,3],
            [16+u(18,24),3-u(16,18)-u(24,28)],//[22,-3],
            [16+u(18,22),3-u(16,18)-u(24,28)], // [20,-3],
            [16+u(18,22),3-u(16,18)], // [20, 1],
            [16+u(18,20),3-u(16,18)],// [18,1],
            [16+u(18,20),3-u(16,18)-u(24,26)],// [18,-1],
            [16+u(18,20)+u(28,30),3-u(16,18)-u(24,26)], // [20,-1],
            [16+u(18,20)+u(28,30),3-u(16,18)-u(24,28)], //[20,-3],
            [16,3-u(16,18)-u(24,28)],//
            [],
        ],
        R: [
            [23,3-u(22,24)-u(30,34)], // [23,-3],
            [23,3],
            [23+u(24,30),3], // [29,3],
            [23+u(24,30),3-u(22,24)-0.8*u(30,32)], // [29,-0.6],
            [23+u(24,28),3-u(22,24)-0.8*u(30,32)], // [27,-0.6],
            [23+u(24,28)+u(34,36),3-u(22,24)-0.8*u(30,32)-1.2*u(34,36)],  // [29,-3],
            [23+u(24,28)-u(32,34)+u(34,36),3-u(22,24)-0.8*u(30,32)-1.2*u(34,36)], // [27,-3],
            [23+u(24,28)-u(32,34),3-u(22,24)-0.8*u(30,32)], // [25,-0.6],
            [23+u(24,28)-u(32,34),3-u(22,24)-0.2*u(30,32)], // [25,0.6],
            [23+u(24,28),3-u(22,24)-0.2*u(30,32)], // [27,0.6],
            [23+u(24,28),3-u(22,24)], // [27,1],
            [23+u(24,26),3-u(22,24)], // [25,1],
            [23+u(24,26),3-u(22,24)-u(30,34)], // [25,-3],
            [],
        ],
        T: [
            [5.5,3-u(0,2)], // [5.5,1],
            [5.5,3], // [5.5,3],
            [5.5+0.875*u(2,6),3], // [9,3],
            [5.5+0.875*u(2,6),3-u(0,2)], // [9,1],
            [], // 0.875
        ],
        E: [
            [10,3],
            [10,3-u(4,6)-u(12,16)], // [10,-3],
            [10+u(6,8)+u(20,24),3-u(4,6)-u(12,16)], // [16,-3],
            [10+u(6,8)+u(20,24),3-u(4,6)-u(12,14)], // [16,-1],
            [10+u(6,8),3-u(4,6)-u(12,14)], // [12,-1],
            [10+u(6,8),3-u(4,6)-0.8*u(12,14)], // [12,-0.6],
            [10+u(6,8)+u(16,20),3-u(4,6)-0.8*u(12,14)], // [16,-0.6],
            [10+u(6,8)+u(16,20),3-u(4,6)-0.2*u(12,14)], // [16,0.6],
            [10+u(6,8),3-u(4,6)-0.2*u(12,14)], // [12,0.6],
            [10+u(6,8),3-u(4,6)], // [12,1],
            [10+u(6,12),3-u(4,6)], // [16,1],
            [10+u(6,12),3],
            [],
        ],
        C: [
            [17,3],
            [17+u(12,18),3], // [23,3],
            [17+u(12,18),3-u(10,12)],// [23,1],
            // [19,1],
            // [19,-1],
            // [23,-1],
            // [23,-3],
            [17,3-u(10,12)], // [17,-3],
            [],
        ],
        H: [
            [24,3],
            [26,3],
            [26,0.6],
            [28,0.6],
            [28,3],
            [30,3],
            [30,-3],
            [28,-3],
            [28,-0.6],
            [26,-0.6],
            [26,-3],
            [24,-3],
            []
        ]
    }

    return [
        ...'LASOR'.split('').map(c=>S[c].map(x=>x.length?[x[0]-25*s(t,0,0.65),x[1]]:[])).flat(),
        ...S.L.map(x=>x.length?[-x[0]+6*s(t,0,0.65), -x[1]]:[]),
        ...'TEC'.split('').map(c=>S[c].map(x=>x.length?[x[0]+6*s(t,0,0.65),x[1]]:[])).flat(),
    ];
};


Deno.serve(req => {
    const path = new URL(req.url).pathname;
    // Logo JPEG
    if (path == '/logo.jpg') return serveFile(req, 'logo.jpg');
    // Main Code
    return new Response(/*html*/`
        <!--<img style="position:absolute;left:0;top:0;width:100vmin;aspect-ratio:1/1;z-index:1;opacity:0.5" src="/logo.jpg" />-->
        <svg id="logo" viewBox="0 0 ${size[0]} ${size[1]}" style="position:absolute;left:0;top:0;width:100vmin;aspect-ratio:1/1;z-index:2;overflow:visible">
            <defs>
                <filter id="label_shadow">
                    <feMorphology in="SourceAlpha" operator="dilate" radius="1" result="extended" />

                    <!-- White Shadow -->
                    <feFlood flood-color="#fff" result="shw_0" />
                    <feOffset in="extended" dx="0.5" dy="0.5" result="shw_1" />
                    <feComposite operator="out" in="shw_0" in2="shw_1" />
                    <feMorphology operator="dilate" radius="1" />
                    <feGaussianBlur stdDeviation="1" result="shw_2" />

                    <!-- Black Shadow -->
                    <feFlood flood-color="#000" result="shb_0" />
                    <feOffset in="extended" dx="-0.5" dy="-0.5" result="shb_1" />
                    <feComposite operator="out" in="shb_0" in2="shb_1" />
                    <feMorphology operator="dilate" radius="1" />
                    <feGaussianBlur stdDeviation="1" result="shb_2" />

                    <!-- Merging Shadow -->
                    <feMerge>
                        <feMergeNode in="shw_2" />
                        <feMergeNode in="shb_2" />
                    </feMerge>
                    <feComposite operator="atop" in2="SourceGraphic" />
                </filter>
            </defs>
            <path fill-rule="evenodd" stroke="red" stroke-width="0.4" fill="#FE0000" filter="url(#label_shadow)">
                <!-- Loading Animation -->
                <animate attributeName="d" values="${render(animation)}" dur="1s" repeatCount="indefinite" />
            </path>
        </svg>
    `, {status: 200, headers: { 'content-type':'text/html' }})
});