#!/usr/bin/env -S deno run -A --watch
import { UI, shape_argf, svg } from './ui';

const L = (u:shape_argf) => [
    [0,9],
    [-7, -3.25],
    [1.75, -2],
    [2.5, -0],
    [-3.5, -0.75],
    [],
];

const _logo = new UI({
    matrix: [5,0,0,5,0,0],
    def: [
        svg`<filter id="label_shadow">
            <feMorphology in="SourceAlpha" operator="dilate" radius="1" result="extended" />

            <!-- White Shadow -->
            <feFlood flood-color="#fff" result="shw_0" />
            <feOffset in="extended" dx="0.25" dy="0.25" result="shw_1" />
            <feComposite operator="out" in="shw_0" in2="shw_1" />
            <feMorphology operator="dilate" radius="1" />
            <feGaussianBlur stdDeviation="1" result="shw_2" />

            <!-- Black Shadow -->
            <feFlood flood-color="#000" result="shb_0" />
            <feOffset in="extended" dx="-0.25" dy="-0.25" result="shb_1" />
            <feComposite operator="out" in="shb_0" in2="shb_1" />
            <feMorphology operator="dilate" radius="1" />
            <feGaussianBlur stdDeviation="1" result="shb_2" />

            <!-- Merging Shadow -->
            <feMerge>
                <feMergeNode in="shw_2" />
                <feMergeNode in="shb_2" />
            </feMerge>
            <feComposite operator="atop" in2="SourceGraphic" />
        </filter>`,
    ],
    shape: u => [
        
        { fill:'#FE0000', filter:'label_shadow', debug:false, path: [ // Lightning
            ...L(u),
            ...L(u).map(x=>x.map(y=>-y)),
        ]},
    ]
});