#!/usr/bin/env -S deno run -A --watch
import { UI, svg, shape_argf } from './ui';

const L = (u:shape_argf) => [
    [0,9],
    [-7, -3.25],
    [1.75, -2],
    [2.5, -0],
    [-3.5, -0.75],
    [],
];
const L2 = (u:shape_argf) => [
    [1,9.5],
    [-6, 0.25],
    //[1.75, 0],
    [6, 0.25],
    [-1, 2.5],
    [],
];


const logos = [
    /* ATTEMPT #0 */
    new UI({
        matrix: [8.25,2,0,-8.25,0,0],
        width: 650,
        height: 50,
        time: 5,
        animation: {
            loading: { start:-12, end:0 },
            titlecard: { start:0, end:36 }
        },
        debug:true,
        def: [
            // White top and Black bottom shadow
            svg`<filter id="svg_shadow">
                <feMorphology in="SourceAlpha" operator="dilate" radius="1" result="extended" />
    
                ${/* White Shadow */''}
                <feFlood flood-color="#fff" result="shw_0" />
                <feOffset in="extended" dx="0.25" dy="0.25" result="shw_1" />
                <feComposite operator="out" in="shw_0" in2="shw_1" />
                <feMorphology operator="dilate" radius="1" />
                <feGaussianBlur stdDeviation="1" result="shw_2" />
    
                ${/* Black Shadow */''}
                <feFlood flood-color="#000" result="shb_0" />
                <feOffset in="extended" dx="-0.25" dy="-0.25" result="shb_1" />
                <feComposite operator="out" in="shb_0" in2="shb_1" />
                <feMorphology operator="dilate" radius="1" />
                <feGaussianBlur stdDeviation="1" result="shb_2" />
    
                ${/* Mergin Shadow */''}
                <feMerge>
                    <feMergeNode in="shw_2" />
                    <feMergeNode in="shb_2" />
                </feMerge>
                <feComposite operator="atop" in2="SourceGraphic" />
            </filter>`,
            // Silver texture
            svg`<linearGradient id="svg_silver" gradientTransform="rotate(135) translate(-0.45 0)">
                <stop offset="0" stop-color="#000" />
                <stop offset="25%" stop-color="#545454" />
                <stop offset="45%" stop-color="#fff" />
                <stop offset="55%" stop-color="#fff" />
                <stop offset="75%" stop-color="#545454" />
                <stop offset="100%" stop-color="#000" />
            </linearGradient>`,
            // Mask of shape over circle
            svg`<filter id="svg_logo_extrude">
                <feMorphology operator="dilate" radius="5" />
            </filter><mask id="svg_logo_mask">
                <rect x="-100%" y="-100%" width="200%" height="200%" fill="#fff" />
                <use href="#svg_logo" fill="#000" filter="url(#svg_logo_extrude)" />
            </mask>`,
        ],
        shape: u => {
            /** SHAPES */
            const S:{[letter:string]:number[][]} = {
                L: [
                    // BL
                    [3-u(-12,-4),-3],
                    // TL
                    [3-u(-12,-4),-1+u(-4,0)],
                    // TR
                    [3-1.5*u(-8,-4),-1+u(-4,0)],
                    // ML
                    [3-1.5*u(-8,-4),-1],
                    [3-u(-4,-2),-1],
                    // TO INNER TOP RIGHT
                    [3-u(-4,-2),1-u(-6,-4)],
                    // TO BOTTOM OF TOP
                    [-1-u(-4,-2)+u(-12,-8),1-u(-6,-4)],
                    [-1-u(-4,-2)+u(-12,-8),3-u(-8,-4)],
                    [5-u(-4,0),3-u(-8,-4)],
                    // MR
                    [5-u(-4,0),-1],
                    // BR
                    [5-u(-4,0),-3],
                    [],
                ],
                // 6, 4
                A: [
                    [2,-3],
                    [2,-3+u(2,8)],
                    [2+u(0,2)+u(8,12),-3+u(2,8)],
                    [2+u(0,2)+u(8,12),-3+u(4,8)-u(12,16)],
                    [2+u(0,2)+u(10,12),-3+u(4,8)-u(12,16)],
                    [2+u(0,2)+u(10,12),-3+u(4,8)-u(13,16)],
                    [2+u(0,2)+u(10,12)-u(16,18),-3+u(4,8)-u(13,16)],
                    [2+u(0,2)+u(10,12)-u(16,18),-3+u(4,8)-u(15,16)],
                    [2+u(0,2)+u(10,12),-3+u(4,8)-u(15,16)],
                    [2+u(0,2)+u(10,12),-3+u(4,8)],
                    [2+u(0,2),-3+u(4,8)],
                    [2+u(0,2),-3],
                    [],
                ],
                S: [
                    [9,3-u(10,12)-0.8*u(18,20)], //  [9,-0.6],
                    [9,3],              //  [9,3],
                    [9+u(12,18),3],     //  [15,3],
                    [9+u(12,18),3-u(10,12)],     //  [15,1],
                    [9+u(12,14),3-u(10,12)],     //  [11,1],
                    [9+u(12,14),3-u(10,12)-0.2*u(18,20)],    // [11,0.6],
                    [9+u(12,14)+u(20,24),3-u(10,12)-0.2*u(18,20)],    // [15,0.6],
                    [9+u(12,14)+u(20,24),3-u(10,12)-0.8*u(18,20)-1.2*u(24,26)],    // [15,-3],
                    [9+u(12,14)+u(20,22)-u(26,30),3-u(10,12)-0.8*u(18,20)-1.2*u(24,26)], // [9,-3],
                    [9+u(12,14)+u(20,22)-u(26,30),3-u(10,12)-0.8*u(18,20)-0.4*u(24,26)], /*[9,-1],*/
                    [9+u(12,14)+u(20,22),3-u(10,12)-0.8*u(18,20)-0.4*u(24,26)], //[13,-1],
                    [9+u(12,14)+u(20,22),3-u(10,12)-0.8*u(18,20)], // [13,-0.6],
                    [],
                ],
                O: [
                    [16,3-u(16,18)],
                    [16,3],
                    [16+u(18,24),3],//[22,3],
                    [16+u(18,24),3-u(16,18)-u(24,28)],//[22,-3],
                    [16+u(18,22),3-u(16,18)-u(24,28)], // [20,-3],
                    [16+u(18,22),3-u(16,18)], // [20, 1],
                    [16+u(18,20),3-u(16,18)],// [18,1],
                    [16+u(18,20),3-u(16,18)-u(24,26)],// [18,-1],
                    [16+u(18,20)+u(28,30),3-u(16,18)-u(24,26)], // [20,-1],
                    [16+u(18,20)+u(28,30),3-u(16,18)-u(24,28)], //[20,-3],
                    [16,3-u(16,18)-u(24,28)],//
                    [],
                ],
                R: [
                    [23,3-u(22,24)-u(30,34)], // [23,-3],
                    [23,3],
                    [23+u(24,30),3], // [29,3],
                    [23+u(24,30),3-u(22,24)-0.8*u(30,32)], // [29,-0.6],
                    [23+u(24,28),3-u(22,24)-0.8*u(30,32)], // [27,-0.6],
                    [23+u(24,28)+u(34,36),3-u(22,24)-0.8*u(30,32)-1.2*u(34,36)],  // [29,-3],
                    [23+u(24,28)-u(32,34)+u(34,36),3-u(22,24)-0.8*u(30,32)-1.2*u(34,36)], // [27,-3],
                    [23+u(24,28)-u(32,34),3-u(22,24)-0.8*u(30,32)], // [25,-0.6],
                    [23+u(24,28)-u(32,34),3-u(22,24)-0.2*u(30,32)], // [25,0.6],
                    [23+u(24,28),3-u(22,24)-0.2*u(30,32)], // [27,0.6],
                    [23+u(24,28),3-u(22,24)], // [27,1],
                    [23+u(24,26),3-u(22,24)], // [25,1],
                    [23+u(24,26),3-u(22,24)-u(30,34)], // [25,-3],
                    [],
                ],
                T: [
                    [5.5,3-u(0,2)], // [5.5,1],
                    [5.5,3], // [5.5,3],
                    [5.5+0.875*u(2,6),3], // [9,3],
                    [5.5+0.875*u(2,6),3-u(0,2)], // [9,1],
                    [], // 0.875
                ],
                E: [
                    [10,3],
                    [10,3-u(4,6)-u(12,16)], // [10,-3],
                    [10+u(6,8)+u(20,24),3-u(4,6)-u(12,16)], // [16,-3],
                    [10+u(6,8)+u(20,24),3-u(4,6)-u(12,14)], // [16,-1],
                    [10+u(6,8),3-u(4,6)-u(12,14)], // [12,-1],
                    [10+u(6,8),3-u(4,6)-0.8*u(12,14)], // [12,-0.6],
                    [10+u(6,8)+u(16,20),3-u(4,6)-0.8*u(12,14)], // [16,-0.6],
                    [10+u(6,8)+u(16,20),3-u(4,6)-0.2*u(12,14)], // [16,0.6],
                    [10+u(6,8),3-u(4,6)-0.2*u(12,14)], // [12,0.6],
                    [10+u(6,8),3-u(4,6)], // [12,1],
                    [10+u(6,12),3-u(4,6)], // [16,1],
                    [10+u(6,12),3],
                    [],
                ],
                C: [
                    [17,3],
                    [17+u(12,18),3], // [23,3],
                    [17+u(12,18),3-u(10,12)],// [23,1],
                    // [19,1],
                    // [19,-1],
                    // [23,-1],
                    // [23,-3],
                    [17,3-u(10,12)], // [17,-3],
                    [],
                ],
                H: [
                    [24,3],
                    [26,3],
                    [26,0.6],
                    [28,0.6],
                    [28,3],
                    [30,3],
                    [30,-3],
                    [28,-3],
                    [28,-0.6],
                    [26,-0.6],
                    [26,-3],
                    [24,-3],
                    []
                ]
            }
            return [
                /** Back Circle */
                { fill:'url(#svg_silver)', mask:'svg_logo_mask', filter:'svg_shadow', debug:false, path:[
                    [0,5],
                    [5,5,0,0,0,0,-5],
                    [5,5,0,0,0,0,5],
                ]},
                /** Main Shape */
                { id:'svg_logo', fill:'#FE0000', filter:'svg_shadow', debug:false, path:[
                    ...'LASOR'.split('').map(c=>S[c].map(x=>x.length?[x[0]-u(0,30)/1.2,-x[1]]:[])).flat(),
                    ...S.L.map(x=>x.length?[-x[0]+u(0,30)/5, x[1]]:[]),
                    ...'TEC'.split('').map(c=>S[c].map(x=>x.length?[x[0]+u(0,30)/5,-x[1]]:[])).flat(),
                ]}
            ]
        },

    }),
    /* ATTEMPT #1 */
    new UI({
        matrix: [8,0,0,8,0,0],
        back: '#000',
        def: [
            /* Animating RGB Gradient */
            svg`<linearGradient id="def_rgb" x1="0%" y1="0%" x2="100%" y="0%">
                <stop offset="0%" stop-color="#ff0080">
                    <animate attributeName="stop-color" values="#ff0080;#00ffff;#ffff00;#ff0080" dur="4s" repeatCount="indefinite"/>
                </stop>
                <stop offset="100%" stop-color="#00ffff">
                    <animate attributeName="stop-color" values="#00ffff;#ffff00;#ff0080;#00ffff" dur="4s" repeatCount="indefinite"/>
                </stop>
            </linearGradient>`,
            /* Laser Masking */
            svg`<filter id="extrude">
                <feMorphology operator="dilate" radius="2" />
            </filter><mask id="def_lasermask">
                <rect x="0" y="0" width="100%" height="100%" fill="#fff" />
                <use href="#laser" fill="#000" filter="url(#extrude)" />
            </mask>`
        ],
        shape: u => [
            { fill:'url(#def_rgb)', path:[ // Bottom Layer
                // South
                [-5,-3],
                [-3,-5],
                [5,-5],
                [3,-3],
                [],
                // North
                [-5,5],
                [-3,3],
                [5,3],
                [3,5],
                [],
                // Center
                [2,-0.5],
                [2,-2],
                [-1,-2],
                [-2,-1],
                [-2,-0.5],
                [-0.5,-0.5],
                []
            ]},
            { fill:'#fff', mask:'def_lasermask', path: [ // Top Layer
                // West
                [-5,4],
                [-3,2],
                [-3,-5],
                [-5,-3],
                [],
                // East
                [3,5],
                [5,3],
                [5,-4],
                [3,-2],
                [],
                // Center
                [-2,0.5],
                [-2,2],
                [1,2],
                [2,1],
                [2,-0.5],
                [0.5,-0.5],
                [0.5,0.5],
                []
            ]},
            { id:'laser', fill:'url(#def_rgb)', path:[ // Laser Layer
                [-4,2],
                [-3.5,0.5,-3.5,0.5,-2,0],
                //[-3.5,0.5],
                //[-2,0],
                [-3.5,-0.5],
                [-4,-2],
                [-4.5,-0.5],
                [-6,0],
                [-4.5,0.5],
                [],
            ]},
        ]
    }),
    /* Attempt #2 */
    new UI({
        matrix: [5,0,0,5,0,0],
        def: [
            // White top and Black bottom shadow
            svg`<filter id="svg_shadow">
                <feMorphology in="SourceAlpha" operator="dilate" radius="1" result="extended" />
    
                ${/* White Shadow */''}
                <feFlood flood-color="#fff" result="shw_0" />
                <feOffset in="extended" dx="0.25" dy="0.25" result="shw_1" />
                <feComposite operator="out" in="shw_0" in2="shw_1" />
                <feMorphology operator="dilate" radius="1" />
                <feGaussianBlur stdDeviation="1" result="shw_2" />
    
                ${/* Black Shadow */''}
                <feFlood flood-color="#000" result="shb_0" />
                <feOffset in="extended" dx="-0.25" dy="-0.25" result="shb_1" />
                <feComposite operator="out" in="shb_0" in2="shb_1" />
                <feMorphology operator="dilate" radius="1" />
                <feGaussianBlur stdDeviation="1" result="shb_2" />
    
                ${/* Mergin Shadow */''}
                <feMerge>
                    <feMergeNode in="shw_2" />
                    <feMergeNode in="shb_2" />
                </feMerge>
                <feComposite operator="atop" in2="SourceGraphic" />
            </filter>`,
            // Silver texture
            svg`<linearGradient id="svg_silver" gradientTransform="rotate(135) translate(-0.45 0)">
                <stop offset="0" stop-color="#000" />
                <stop offset="25%" stop-color="#545454" />
                <stop offset="45%" stop-color="#fff" />
                <stop offset="55%" stop-color="#fff" />
                <stop offset="75%" stop-color="#545454" />
                <stop offset="100%" stop-color="#000" />
            </linearGradient>`,
            // Mask of shape over circle
            svg`<filter id="extrude">
                <feMorphology operator="dilate" radius="2" />
            </filter><mask id="top_sub">
                <rect x="0" y="0" width="100" height="100" fill="#fff" />
                <use href="#logo" fill="#000" filter="url(#extrude)" />
            </mask>`,
            /* Animating RGB Gradient */
            svg`<linearGradient id="def_rgb" x1="0%" y1="0%" x2="100%" y="0%">
                <stop offset="0%" stop-color="#ff0080">
                    <animate attributeName="stop-color" values="#ff0080;#00ffff;#ffff00;#ff0080" dur="4s" repeatCount="indefinite"/>
                </stop>
                <stop offset="100%" stop-color="#00ffff">
                    <animate attributeName="stop-color" values="#00ffff;#ffff00;#ff0080;#00ffff" dur="4s" repeatCount="indefinite"/>
                </stop>
            </linearGradient>`,
        ],
        shape: u => [
            // Back circle
            { fill:'url(#svg_silver)', mask:'top_sub', filter:'svg_shadow', debug:false, path:[
                [0,8],
                [8,8,0,0,0,0,-8],
                [8,8,0,0,0,0,8],
            ]},
            { fill:'none', mask:'top_sub', stroke:'#000A', debug:false, path:[
                [0,8],
                [8,8,0,0,0,0,-8],
                [8,8,0,0,0,0,8],
            ]},
            { id:'logo', fill:'#FE0000', filter:'svg_shadow', debug:false, path: [ // Lightning
                ...L(u),
                ...L(u).map(x=>x.map(y=>-y)),
            ]},
            { fill:'none', stroke:'#fff', debug:false, path: [ // Lightning
                ...L(u),
                ...L(u).map(x=>x.map(y=>-y)),
            ]},
            { fill:'none', stroke:'#000D', debug:false, path: [ // Lightning
                ...L(u),
                ...L(u).map(x=>x.map(y=>-y)),
            ]},
        ]
    }),
    /* Attempt #3 */
    new UI({
        matrix: [5,0,0,5,0,0],
        def: [
            // White top and Black bottom shadow
            svg`<filter id="svg_shadow">
                <feMorphology in="SourceAlpha" operator="dilate" radius="1" result="extended" />
    
                ${/* White Shadow */''}
                <feFlood flood-color="#fff" result="shw_0" />
                <feOffset in="extended" dx="0.25" dy="0.25" result="shw_1" />
                <feComposite operator="out" in="shw_0" in2="shw_1" />
                <feMorphology operator="dilate" radius="1" />
                <feGaussianBlur stdDeviation="1" result="shw_2" />
    
                ${/* Black Shadow */''}
                <feFlood flood-color="#000" result="shb_0" />
                <feOffset in="extended" dx="-0.25" dy="-0.25" result="shb_1" />
                <feComposite operator="out" in="shb_0" in2="shb_1" />
                <feMorphology operator="dilate" radius="1" />
                <feGaussianBlur stdDeviation="1" result="shb_2" />
    
                ${/* Mergin Shadow */''}
                <feMerge>
                    <feMergeNode in="shw_2" />
                    <feMergeNode in="shb_2" />
                </feMerge>
                <feComposite operator="atop" in2="SourceGraphic" />
            </filter>`,
            // Silver texture
            svg`<linearGradient id="svg_silver" gradientTransform="rotate(135) translate(-0.45 0)">
                <stop offset="0" stop-color="#000" />
                <stop offset="25%" stop-color="#545454" />
                <stop offset="45%" stop-color="#fff" />
                <stop offset="55%" stop-color="#fff" />
                <stop offset="75%" stop-color="#545454" />
                <stop offset="100%" stop-color="#000" />
            </linearGradient>`,
            // Mask of shape over circle
            svg`<filter id="extrude">
                <feMorphology operator="dilate" radius="2" />
            </filter><mask id="top_sub">
                <rect x="0" y="0" width="100" height="100" fill="#fff" />
                <use href="#logo" fill="#000" filter="url(#extrude)" />
            </mask>`,
            /* Animating RGB Gradient */
            svg`<linearGradient id="def_rgb" x1="0%" y1="0%" x2="100%" y="0%">
                <stop offset="0%" stop-color="#ff0080">
                    <animate attributeName="stop-color" values="#ff0080;#00ffff;#ffff00;#ff0080" dur="4s" repeatCount="indefinite"/>
                </stop>
                <stop offset="100%" stop-color="#00ffff">
                    <animate attributeName="stop-color" values="#00ffff;#ffff00;#ff0080;#00ffff" dur="4s" repeatCount="indefinite"/>
                </stop>
            </linearGradient>`,
        ],
        shape: u => [
            // Back circle
            { fill:'url(#svg_silver)', mask:'top_sub', filter:'svg_shadow', debug:false, path:[
                [0,8],
                [8,8,0,0,0,0,-8],
                [8,8,0,0,0,0,8],
            ]},
            { fill:'none', mask:'top_sub', stroke:'#000A', debug:false, path:[
                [0,8],
                [8,8,0,0,0,0,-8],
                [8,8,0,0,0,0,8],
            ]},
            { id:'logo', fill:'#FE0000', filter:'svg_shadow', debug:false, path: [ // Lightning
                ...L2(u),
                ...L2(u).map(x=>x.map(y=>-y)),
            ]},
            { fill:'none', stroke:'#fff', debug:false, path: [ // Lightning
                ...L2(u),
                ...L2(u).map(x=>x.map(y=>-y)),
            ]},
            { fill:'none', stroke:'#000D', debug:false, path: [ // Lightning
                ...L2(u),
                ...L2(u).map(x=>x.map(y=>-y)),
            ]},
        ]
    })
];

UI.host(logos[0]);