#!/usr/bin/env -S deno run -A --watch

export function html(strings:TemplateStringsArray, ...values:(string|number)[]):string {
    return strings.reduce((out:string, str:string, n:number) => out + str + (values[n] ?? ''), '').split('\n').map(x=>x.trim()).join('');
}
export const svg = html;

export type shape_argf = (a:number,b:number)=>number;
export type shape_type = {
    fill:string,
    path:number[][],
    debug?:boolean,
    code?:string,
    id?:string,
    filter?:string,
    stroke?:string,
    mask?:string
};
export type shape_ani = {
    [name:string]:{
        start:number,
        end:number
    }
};
export type shape_func = (u:shape_argf)=>shape_type[];
export type config_type = {
    width?:number,
    height?:number,
    back?:string,
    shape?:shape_func,
    matrix?:number[],
    def?:string[],
    time?:number,
    animation?:shape_ani,
    debug?:boolean
};


export class UI {
    name:string = 'Graphics';
    width:number = 100;
    height:number = 100;
    back:string|null = '#fff';
    shape:shape_func = _=>[];
    matrix:number[] = [1,0,0,1,0,0];
    def:string[] = [];
    svg:string;
    time:number = 1;
    digits:number = 2;
    frames:number[]|null = null;

    animate(start:number|null=null, end:number|null=null, time:number|null=null):string {
        /* ----- CALCULATE FRAMES ----- */
        if (this.frames == null) {
            this.frames = [];
            const get_frames = (start:number, end:number):number => {
                if (this.frames == null) this.frames = [];
                if (!this.frames.includes(start)) this.frames.push(start);
                if (!this.frames.includes(end)) this.frames.push(end);
                return 0;
            };
            this.shape(get_frames);
            this.frames.sort((a,b)=>a-b);
            if (!this.frames.length) this.frames.push(0);
        }

        /** ----- CALCULATE KEYTIMES ----- */
        if (start == null) start = this.frames[0];
        if (end == null) end = this.frames[this.frames.length-1];
        if (!this.frames.includes(start)) throw new Error(`Animation starting frame ${start} not found`);
        if (!this.frames.includes(end)) throw new Error(`Animation ending frame ${end} not found`);
        const keytimes = this.frames.slice(this.frames.indexOf(start), this.frames.indexOf(end)+1).map(x=>Math.floor(1000*(x-start)/(end-start))/1000).join(';');
        console.log(keytimes);

        /* ----- RENDER PATH ----- */
        const mul = (p:number[]) => [
            Math.floor(Math.pow(10,this.digits)*(/*this.width/2 +*/this.matrix[0]*p[0]+this.matrix[1]*p[1]+this.matrix[4]))/Math.pow(10,this.digits),
            Math.floor(Math.pow(10,this.digits)*(/*this.height/2-*/this.matrix[2]*p[0]-this.matrix[3]*p[1]-this.matrix[5]))/Math.pow(10,this.digits),
        ];
        const frames = this.frames.map(f => {
            const shapes = this.shape((a,b)=>(b-a)*(f<=a?0:f>=b?1:(f-a)/(b-a)))
            for (const shape of shapes) {
                shape.code = shape.path.map((x,n,a) =>
                    (n?'':'M')+
                    (x.length==2?mul(x).join(' '):!x.length?'Z'+(n+1==a.length?'':'M'):'')+
                    (x.length==6?`C${x.reduce((a,_,n)=>n%2?a:[...a,[x[n],x[n+1]]] as [number,number][],[] as [number,number][]).map(x=>`${x[0]} ${x[1]}`).join(' ')}M`:'')+
                    (x.length==7?`A${this.matrix[0]*x[0]} ${this.matrix[3]*x[1]} ${x.slice(2,5).join(' ')} ${mul(x.slice(5,7)).join(' ')}`:'')
                ).reduce((p,v)=>p+(!p.endsWith(' ')&&/^[\d-]/.test(v)?' ':'')+v, '');
            }
            return shapes;
        });
        const shapes = frames[0].map((_,n)=>frames.map(x=>x[n]));
        return shapes.map(shape => {
            const style = `fill="${shape[0].fill}"`
                +(shape[0].filter ? ` filter="url(#${shape[0].filter})"` : '')
                +(shape[0].stroke?` stroke="${shape[0].stroke}" stroke-linejoin="round"` : '')
                +(shape[0].mask?` mask="url(#${shape[0].mask})"` : '');
            const code = [svg`
                <path${shape[0].id?` id="${shape[0].id}"` : ''} fill-rule="evenodd" ${shape[0].debug ? `stroke="red" stroke-width="0.4" fill="none"` : shape[0].id ? '' : style}>
                    <animate attributeName="d" values="${shape.map(x=>x.code).join(';')}" keyTimes="${keytimes}" dur="${this.time}s" repeatCount="indefinite" />
                </path>
            `,svg`
                <use href="#${shape[0].id!}" ${style} />
            `];
            if (shape[0].id) {
                console.log('DEF', code[0]);
                this.def.push(code[0]); 
                return code[1];
            }
            return code[0];
        }).join('');
    }

    constructor(config:config_type={}) {
        /* ----- SET UP CONFIGURATIONS ----- */
        if ('width' in config) this.width = config.width!;
        if ('height' in config) this.height = config.height!;
        if ('back' in config) this.back = config.back!;
        if ('shape' in config) this.shape = config.shape!;
        if ('matrix' in config) this.matrix = config.matrix!;
        if ('def' in config) this.def = config.def!;
        if ('time' in config) this.time = config.time!;

        /* ----- CALCULATE FRAMES ----- *

        const frame_nums:number[] = [];
        const get_frames = (start:number, end:number):number => {
            if (!frame_nums.includes(start)) frame_nums.push(start);
            if (!frame_nums.includes(end)) frame_nums.push(end);
            return 0;
        };
        this.shape(get_frames);
        frame_nums.sort((a,b)=>a-b);
        if (config.debug) console.log(frame_nums);
        
        /** ----- CALCULATE KEYTIMES ----- *
        const frames_num = (frame_nums[frame_nums.length-1]??0)-(frame_nums[0]??0);
        const keytimes = frame_nums.map((x,_,a)=>Math.floor(1000*(x-a[0])/frames_num)/1000).join(';');
        console.log(keytimes);

        /* ----- RENDER PATH ----- *
        const mul = (p:number[]) => [
            Math.floor(Math.pow(10,this.digits)*(/*this.width/2 +*this.matrix[0]*p[0]+this.matrix[1]*p[1]+this.matrix[4]))/Math.pow(10,this.digits),
            Math.floor(Math.pow(10,this.digits)*(/*this.height/2-*this.matrix[2]*p[0]-this.matrix[3]*p[1]-this.matrix[5]))/Math.pow(10,this.digits),
        ];
        if (!frame_nums.length) frame_nums.push(0);
        const frames = frame_nums.sort((a,b)=>a-b).map(f => {
            const shapes = this.shape((a,b)=>(b-a)*(f<=a?0:f>=b?1:(f-a)/(b-a)))
            for (const shape of shapes) {
                shape.code = shape.path.map((x,n,a) =>
                    (n?'':'M')+
                    (x.length==2?mul(x).join(' '):!x.length?'Z'+(n+1==a.length?'':'M'):'')+
                    (x.length==6?`C${x.reduce((a,_,n)=>n%2?a:[...a,[x[n],x[n+1]]] as [number,number][],[] as [number,number][]).map(x=>`${x[0]} ${x[1]}`).join(' ')}M`:'')+
                    (x.length==7?`A${this.matrix[0]*x[0]} ${this.matrix[3]*x[1]} ${x.slice(2,5).join(' ')} ${mul(x.slice(5,7)).join(' ')}`:'')
                ).reduce((p,v)=>p+(!p.endsWith(' ')&&/^[\d-]/.test(v)?' ':'')+v, '');
            }
            return shapes;
        });
        const shapes = frames[0].map((_,n)=>frames.map(x=>x[n]));
        const shapes_code = shapes.map(shape => {
            const style = `fill="${shape[0].fill}"`
                +(shape[0].filter ? ` filter="url(#${shape[0].filter})"` : '')
                +(shape[0].stroke?` stroke="${shape[0].stroke}" stroke-linejoin="round"` : '')
                +(shape[0].mask?` mask="url(#${shape[0].mask})"` : '');
            const code = [svg`
                <path${shape[0].id?` id="${shape[0].id}"` : ''} fill-rule="evenodd" ${shape[0].debug ? `stroke="red" stroke-width="0.4" fill="none"` : shape[0].id ? '' : style}>
                    <animate attributeName="d" values="${shape.map(x=>x.code).join(';')}" keyTimes="${keytimes}" dur="${this.time}s" repeatCount="indefinite" />
                </path>
            `,svg`
                <use href="#${shape[0].id!}" ${style} />
            `];
            if (shape[0].id) {
                this.def.push(code[0]); 
                return code[1];
            }
            return code[0];
        });*/

        const shapes = this.animate();
        this.svg = html`
            <svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid meet" width="100%" height="100%" viewBox="${-this.width/2} ${-this.height/2} ${this.width} ${this.height}">
                ${this.def.length ? '<defs>':''}
                    ${this.def.join('\n')}
                ${this.def.length ? '</defs>':''}
                ${this.back != null ? svg`<rect x="0" y="0" width="${this.width}" height="${this.height}" fill="${this.back}" />` : ''}
                ${shapes/*shapes.map((shape,n) => shapes_code[n][shape[0].id ? 1 : 0]).join('')*/}
            </svg>
        `;
    }

    host() {
        Deno.serve(req => {
            const path = new URL(req.url).pathname;
            if (path == '/svg') return new Response(this.svg, {
                status: 200,
                headers: { 'content-type':'image/svg+xml' }
            });
            return new Response(html`
                <!DOCTYPE html>
                <html>
                    <head>
                        <title>${this.name}</title>
                        <style>html,body{width:100%;height:100%}body{margin:0;background:#111;display:flex;align-items:center;justify-content:center}svg{box-shadow:0 0 10px #222;margin:auto}</style>
                    </head>
                    <body>
                        ${this.svg}
                    </body>
                </html>
            `, {
                status: 200,
                headers: { 'content-type':'text/html' }
            });
        });
    }

    static host(...uis:UI[]) {
        Deno.serve(req => {
            const path = new URL(req.url).pathname;
            if (path.length > 1 && !Number.isNaN(Number(path.slice(1)))) return new Response(uis[Number(path.slice(1))].svg, {
                status: 200,
                headers: { 'content-type':'image/svg+xml' }
            })
            return new Response(html`
                <!DOCTYPE html>
                <html>
                    <head>
                        <title>UI Showcase</title>
                        <style>html,body{width:100%;height:100%}body{margin:0;background:#111;display:flex;align-items:center;justify-content:center;flex-direction:column}svg{flex-shrink:0;box-shadow:0 0 10px #222;margin:auto;width:100vw;height:100vh}</style>
                    </head>
                    <body>
                        ${uis.map(x=>x.svg).join('\n')}
                    </body>
                </html>
            `, {
                status: 200,
                headers: { 'content-type':'text/html' }
            });
        });
    }
}