#!/usr/bin/env -S deno run -A

import puppeteer from 'npm:puppeteer-core';
import StealthPlugin from 'npm:puppeteer-extra-plugin-stealth';

puppeteer.use(StealthPlugin());

const browser = await puppeteer.launch({ headless: false });
const page = await browser.newPage();
await page.goto('https://example.com');