#!/usr/bin/env -S deno run -A --watch
/** # LasorTech Server
  * The **LasorTech server** is the OJT Software Project that provides a server for LasorTech to promote themselves online, it captures company and product details from multiple platforms to provide all of them in a single platform for customer to easily contact, check, and trust.
  * ## TODO
  * - [ ] Company General Purpose Logo Entity
  *   - [ ] Default Static Square Logo
  *   - [ ] Animating Loading version
  *   - [ ] Animating Titlecard version
  *   - [ ] Possibly different versions for errors or events
  * - [ ] Scrapping system to scrap or use the APIs from multiple platforms and store them in a cache like SQLite
  *   - [ ] Caching system through SQLite
  *   - [ ] Scrapping Shoppee
  *   - [ ] Scrapping QuickBook
  * - [ ] Multi-Platform Device support
  *   - [ ] Mobile/IPhones
  *   - [ ] Accessibility Design
  *   - [ ] Google SEO
  * @module 
  */
import sass from 'https://deno.land/x/denosass@1.0.6/mod.ts';
import puppeteer, {Browser, Page} from "npm:puppeteer-core";

/** # XML minifier */
function xml(strings:TemplateStringsArray, ...values:(string|number)[]):string {
    return strings.reduce((out:string, str:string, n:number) => out + str.split('\n').map(x=>x.trim()).join('') + (values[n] ?? ''), '');
}

/** # Web Scrapper */
export class Scrapper {
    userdata:string = 'userdata';
    chrome:string = 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';
    debug:boolean = true;
    browser:Browser|null = null;
    site:Page|null = null;

    constructor() {
        
    }
    async start() {
        this.browser = await puppeteer.launch({
            executablePath: this.chrome,
            headless: !this.debug,
            userDataDir: this.userdata,
        });
        this.site = await this.browser.newPage();
        await this.site.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36');
        await this.site.setViewport({ width: 1280, height: 800 });
        await this.site.emulateTimezone("America/New_York");
        await this.site.evaluateOnNewDocument(() => {
            Object.defineProperty(navigator, "webdriver", { get: () => false });
        });

        await this.site.goto('https://shopee.ph/lasortech_ph');
        
        await this.site.waitForSelector('form');
        console.log(await this.site.title());
        await (new Promise<void>(x=>setTimeout(()=>x(), 10000)));
    }
}

/** # Shopee Web Scraper */
export class Shopee extends Scrapper {
    //}$Av7>3~Qf66
}

/** # Graphics Specializer for SVG or HTML Canvas */
export class Graphics {
    constructor(defaults:Partial<Graphics>={}) {
        // Set defaults
        Object.assign(this, defaults);
        this.render();
    }
    render() {
        // Reset
        this.defs = '';

        // Process effects
        const effect_types:{[id:string]:'fill'|'filter'|'mask'} = {};
        let filter_tmp_id:number = 0;
        for (const name in this.effects) {
            const effect = this.effects[name];
            /** Current type */
            let type:''|'fill'|'filter'|'mask' = '';
            /** Temporary filter code */
            let filter = '';
            /** Generates Filter DEF code from `filter` */
            const to_filter = (tmp?:boolean) => {
                const id = tmp ? `t${this.prefix}${(filter_tmp_id++).toString(36)}` : `${this.prefix}${name}`;
                this.defs += xml`<filter id="${id}">${filter}</filter>"`
                filter = '';
                return id;
            };
            // Generate type
            for (const step of effect) {
                // Linear Gradient
                if (step[''] === 'gradient' && !type && 'stops' in step && step.stops) {
                    type = 'fill';
                    this.defs += xml`<linearGradient id="${this.prefix}${name}"${step.transform ? ` gradientTransform="${step.transform}"` : ''}>
                        ${step.stops.map((x,n,a)=>{
                            const offset = typeof x != 'string' ? x[1] : a.length != 1 ? 100*n/(a.length-1) : 0;
                            return xml`<stop offset="${offset}%" stop-color="${typeof x == 'string' ? x : x[0]}"/>`;
                        }).join('')}
                    </linearGradient>`;
                }
                // Mask
                else if (step[''] === 'mask' && type != 'fill' && 'from' in step && step.from) {
                    this.defs += xml`<mask id="${this.prefix}${name}">
                        <rect x="0" y="0" width="100%" height="100%" fill="${step.type == 'include' ? '#000' : '#fff'}"/>
                        <use href="#${this.prefix}${step.from}" fill="${step.type == 'include' ? '#fff' : '#000'}"${type == 'filter' ? ` filter="url(#${to_filter(true)})"`:''}/>
                    </mask>`;
                    type = 'mask';
                }
                // SVG MERGE
                else if (step[''] === 'merge' && 'ins' in step && step.ins) {
                    filter += xml`<feMerge>
                        ${step.ins.map(x=>xml`<feMergeNode in="${x}"/>`).join('')}
                    </feMerge>`
                }
                // SVG FILTERS
                else if (!['gradient','mask'].includes(step[''])) {
                    filter += xml`<${[
                        // HTML Tag
                        `fe${step[''].slice(0,1).toUpperCase()}${step[''].slice(1)}`,
                        // Attributes
                        ...Object.keys(step).filter(x=>x.length).map(x=>{
                            // @ts-ignore: Regardless of type it will be string anyway
                            const val = step[x];
                            return `${x}="${String(val)}"`
                        })
                    ].join(' ')}/>`;
                    type = 'filter';
                }
                // Unknown
                else throw new Error('Unknown effect condition');
            }
            if (type == 'filter') to_filter();
            if (type != '') effect_types[name] = type;
            else throw new Error('Un-identified effect type');
        }
        if (this.debug) console.log('\x1b[1;32mDEFINES\x1b[0m:', this.defs);

        // Get Frames (this.frames)
        if (!this.frames.length) {
            const get_frames = (start:number, end:number):number => {
                if (!this.frames.includes(start)) this.frames.push(start);
                if (!this.frames.includes(end)) this.frames.push(end);
                return 0;
            };
            this.shape(get_frames);
            this.frames.sort((a,b)=>a-b);
            if (!this.frames.length) this.frames.push(0);
        }
        // Render Paths
        const mul = (p:number[]) => [
            Math.floor(Math.pow(10,this.digits)*(/*this.width/2 +*/this.matrix[0]*p[0]+this.matrix[1]*p[1]+this.matrix[4]))/Math.pow(10,this.digits),
            Math.floor(Math.pow(10,this.digits)*(/*this.height/2-*/this.matrix[2]*p[0]-this.matrix[3]*p[1]-this.matrix[5]))/Math.pow(10,this.digits),
        ];
        // Generate all of the shape's path for each frames
        const fshapes = this.frames.map(f =>
            this.shape((a,b)=>(b-a)*(f<=a?0:f>=b?1:(f-a)/(b-a))).map(shape => ({
                ...shape,
                code: shape.path.map((x,n,a) =>
                    // Close/New Path
                    (n?'':'M')+
                    // Line To
                    (x.length==2?mul(x).join(' '):!x.length?'Z'+(n+1==a.length?'':'M'):'')+
                    // Bezier Curve To
                    (x.length==6?`C${x.reduce((a,_,n)=>n%2?a:[...a,[x[n],x[n+1]]] as [number,number][],[] as [number,number][]).map(x=>`${x[0]} ${x[1]}`).join(' ')}M`:'')+
                    // Arc To
                    (x.length==7?`A${this.matrix[0]*x[0]} ${this.matrix[3]*x[1]} ${x.slice(2,5).join(' ')} ${mul(x.slice(5,7)).join(' ')}`:'')
                ).reduce((p,v)=>p+(!p.endsWith(' ')&&/^[\d-]/.test(v)?' ':'')+v, '')
            }))
        );
        // Generate all the shape's code
        const shapes = fshapes[0].map(shape => {
            // Attributes
            const attr = [
                ...(shape.fill ? [`fill="${shape.fill}"`] : []),
                ...(shape.stroke ? [`stroke="${shape.stroke}"`] : []),
                ...(shape.effect??[]).reduce((a,x) => (
                    x in effect_types ? [...a, {
                        'fill': `fill="url(#${this.prefix}${x})"`,
                        'filter': `filter="url(#${this.prefix}${x})"`,
                        'mask': `mask="url(#${this.prefix}${x})"`
                    }[effect_types[x]]] : a), [] as string[]
                )
            ].join(' ');
            return attr;
            // TODO GENERATE PATH, ANIMATES, ETC.
        })
        if (this.debug) console.log('\x1b[1;32mSHAPES:\x1b[0m', shapes);

    }
    /* ----- ASSIGNABLE ----- */
    /** Debugging Mode */
    debug:boolean = false;
    /** Matrix transformation of plotted area to actual area */
    matrix:number[] = [1,0,0,1,0,0];
    /** Width of screen */
    width:number = 100;
    /** Height of screen */
    height:number = 100;
    /** Generated shapes based on frame number */
    shape:(u:(a:number,b:number)=>number)=>{
        id?:string,
        fill?:string, stroke?:string,
        effect?:string[],
        debug?:boolean,
        path:number[][],
    }[] = _=>[];
    /** Effects */
    effects:{[id:string]:(
        // Gradient
        {'':'gradient', transform?:string, stops?:(string|[string,number])[]} |
        // Masking
        {'':'mask', type:'include'|'exclude', from:string} |
        // ----- SVG Filter ----- //
        ((
            // <feBlend>
            {'': 'blend', in2: string, mode: 'normal'|'multiply'|'screen'|'overlay'|'darken'|'lighten'|'color-dodge'|'color-burn'|'hard-light'|'soft-light'|'difference'|'exclusion'|'hue'|'saturation'|'color'|'luminosity'} |
            // <feColorMatrix>
            {'': 'colormatrix', type: 'matrix'|'saturate'|'hueRotate'|'luminanceToAlpha', values?: string} |
            // <feComponentTransfer>
            {'': 'componenttransfer'} |
            // <feComposite>
            {'': 'composite', in2: string, operator: 'over'|'in'|'out'|'atop'|'xor'|'lighter'|'arithmetic', k1?: number, k2?: number, k3?: number, k4?: number} |
            // <feConvolveMatrix>
            {'': 'convolvematrix', order?: number, kernelMatrix: string, divisor?: number, bias?: number, targetX?: number, targetY?: number, edgeMode?: 'duplicate'|'wrap'|'none', kernelUnitLength?: number, preserveAlpha?: 'true'|'false'} |
            // <feDiffuseLighting>
            {'': 'diffuselighting', surfaceScale: number, diffuseConstant: number, kernelUnitLength?: number, 'lighting-color'?: string} |
            // <feDisplacementMap>
            {'': 'displacementmap', in2: string, scale: number, xChannelSelector: 'R'|'G'|'B'|'A', yChannelSelector: 'R'|'G'|'B'|'A'} |
            // <feDropShadow>
            {'': 'dropshadow', dx: number, dy: number, stdDeviation: number, 'flood-color'?: string, 'flood-opacity'?: number} |
            // <feFlood>
            {'': 'flood', 'flood-color': string, 'flood-opacity'?: number} |
            // <feGaussianBlur>
            {'': 'gaussianblur', stdDeviation: number, edgeMode?: 'duplicate'|'wrap'|'none'} |
            // <feImage>
            {'': 'image', href: string, preserveAspectRatio?: string, crossorigin?: 'anonymous'|'use-credentials'} |
            // <feMerge>
            {'': 'merge', ins:string[]} |
            // <feMorphology>
            {'': 'morphology', operator: 'erode'|'dilate', radius: number} |
            // <feOffset>
            {'': 'offset', dx: number, dy: number} |
            // <feSpecularLighting>
            {'': 'specularlighting', surfaceScale: number, specularConstant: number, specularExponent: number, kernelUnitLength?: number, 'lighting-color'?: string} |
            // <feTile>
            {'': 'tile'} |
            // <feTurbulence>
            {'': 'turbulence', type: 'turbulence'|'fractalNoise', baseFrequency: number, numOctaves?: number, seed?: number, stitchTiles?: 'stitch'|'noStitch'}
        ) & { in?: string; result?: string })
    )[]} = {};
    /** Animations */
    animations:{[id:string]:number|{
        start:number,
        end:number
    }} = {};
    /** Number of preceeding digit precisions */
    digits:number = 2;
    /** Prefix to prevent HTML ID conflicts */
    prefix:string = Math.random().toString(36).slice(2, 6)+'_';
    /* ----- GENERATED ----- */
    /** SVG Defineds */
    defs:string = '';
    /** Recognized Frames */
    private frames:number[] = [];
    /** SVG Content */
    svg:string = '';
    /** Data URL */
    get data():string {
        return 'data:image/svg+xml;base64,'+btoa(new TextEncoder().encode(xml`
            <!-- SVG CODE -->
        `).reduce((acc, byte) => acc + String.fromCharCode(byte), ''));
    }
}

/** # Website Serve Content */
export class Website {
    constructor() {
        this.server = Deno.serve(_req => {
            return new Response(this.content, {
                status: 200,
                headers: { 'content-type':'text/html' },
            });
        });
    }

    /** Size of a single unit in pixels */
    unit:number = 50;

    /** Logo SVG */
    logo = new Graphics({
        debug: true,
        width: 650,
        height: 50,
        matrix: [8.25, 2, 0, -8.25, 0, 0],
        animations: {
            default: 0,
            loading: {start:-12, end:0},
            title: {start:0, end:36}
        },
        effects: {
            'shadow': [ // White top and Black bottom shadow
                {'':'morphology', in:'SourceAlpha', operator:'dilate', radius:1, result:'extended'},
                // White Shadow
                {'':'flood', 'flood-color':'#fff', result:'shw0'},
                {'':'offset', in:'extended', dx:0.25, dy:0.25, result:'shw1'},
                {'':'composite', operator:'out', in:'shw0', in2:'shw1'},
                {'':'morphology', operator:'dilate', radius:1},
                {'':'gaussianblur', stdDeviation:1, result:'shw2'},
                // Black Shadow
                {'':'flood', 'flood-color':'#000', result:'shb0'},
                {'':'offset', in:'extended', dx:-0.25, dy:-0.25, result:'shb1'},
                {'':'composite', operator:'out', in:'shb0', in2:'shb1'},
                {'':'morphology', operator:'dilate', radius:1},
                {'':'gaussianblur', stdDeviation:1, result:'shb2'},
                // Both
                {'':'merge', ins:['shw2','shb2']},
                {'':'composite', operator:'atop', in2:'SourceGraphic'}
            ],
            'silver': [ // Silver Texture
                {'':'gradient', transform:'rotate(135) translate(-0.45 0)',stops:[
                    '#000','#545454','#fff','#fff','#545454','#000'
                ]}
            ],
            'mask': [ // Mask to subtract logo from circle
                {'':'morphology', operator:'dilate', radius:5},
                {'':'mask', type:'exclude', from:'logo'},
            ]
        },
        shape: u => {
            /** SHAPES */
            const S:{[letter:string]:number[][]} = {
                L: [
                    // BL
                    [3-u(-12,-4),-3],
                    // TL
                    [3-u(-12,-4),-1+u(-4,0)],
                    // TR
                    [3-1.5*u(-8,-4),-1+u(-4,0)],
                    // ML
                    [3-1.5*u(-8,-4),-1],
                    [3-u(-4,-2),-1],
                    // TO INNER TOP RIGHT
                    [3-u(-4,-2),1-u(-6,-4)],
                    // TO BOTTOM OF TOP
                    [-1-u(-4,-2)+u(-12,-8),1-u(-6,-4)],
                    [-1-u(-4,-2)+u(-12,-8),3-u(-8,-4)],
                    [5-u(-4,0),3-u(-8,-4)],
                    // MR
                    [5-u(-4,0),-1],
                    // BR
                    [5-u(-4,0),-3],
                    [],
                ],
                // 6, 4
                A: [
                    [2,-3],
                    [2,-3+u(2,8)],
                    [2+u(0,2)+u(8,12),-3+u(2,8)],
                    [2+u(0,2)+u(8,12),-3+u(4,8)-u(12,16)],
                    [2+u(0,2)+u(10,12),-3+u(4,8)-u(12,16)],
                    [2+u(0,2)+u(10,12),-3+u(4,8)-u(13,16)],
                    [2+u(0,2)+u(10,12)-u(16,18),-3+u(4,8)-u(13,16)],
                    [2+u(0,2)+u(10,12)-u(16,18),-3+u(4,8)-u(15,16)],
                    [2+u(0,2)+u(10,12),-3+u(4,8)-u(15,16)],
                    [2+u(0,2)+u(10,12),-3+u(4,8)],
                    [2+u(0,2),-3+u(4,8)],
                    [2+u(0,2),-3],
                    [],
                ],
                S: [
                    [9,3-u(10,12)-0.8*u(18,20)], //  [9,-0.6],
                    [9,3],              //  [9,3],
                    [9+u(12,18),3],     //  [15,3],
                    [9+u(12,18),3-u(10,12)],     //  [15,1],
                    [9+u(12,14),3-u(10,12)],     //  [11,1],
                    [9+u(12,14),3-u(10,12)-0.2*u(18,20)],    // [11,0.6],
                    [9+u(12,14)+u(20,24),3-u(10,12)-0.2*u(18,20)],    // [15,0.6],
                    [9+u(12,14)+u(20,24),3-u(10,12)-0.8*u(18,20)-1.2*u(24,26)],    // [15,-3],
                    [9+u(12,14)+u(20,22)-u(26,30),3-u(10,12)-0.8*u(18,20)-1.2*u(24,26)], // [9,-3],
                    [9+u(12,14)+u(20,22)-u(26,30),3-u(10,12)-0.8*u(18,20)-0.4*u(24,26)], /*[9,-1],*/
                    [9+u(12,14)+u(20,22),3-u(10,12)-0.8*u(18,20)-0.4*u(24,26)], //[13,-1],
                    [9+u(12,14)+u(20,22),3-u(10,12)-0.8*u(18,20)], // [13,-0.6],
                    [],
                ],
                O: [
                    [16,3-u(16,18)],
                    [16,3],
                    [16+u(18,24),3],//[22,3],
                    [16+u(18,24),3-u(16,18)-u(24,28)],//[22,-3],
                    [16+u(18,22),3-u(16,18)-u(24,28)], // [20,-3],
                    [16+u(18,22),3-u(16,18)], // [20, 1],
                    [16+u(18,20),3-u(16,18)],// [18,1],
                    [16+u(18,20),3-u(16,18)-u(24,26)],// [18,-1],
                    [16+u(18,20)+u(28,30),3-u(16,18)-u(24,26)], // [20,-1],
                    [16+u(18,20)+u(28,30),3-u(16,18)-u(24,28)], //[20,-3],
                    [16,3-u(16,18)-u(24,28)],//
                    [],
                ],
                R: [
                    [23,3-u(22,24)-u(30,34)], // [23,-3],
                    [23,3],
                    [23+u(24,30),3], // [29,3],
                    [23+u(24,30),3-u(22,24)-0.8*u(30,32)], // [29,-0.6],
                    [23+u(24,28),3-u(22,24)-0.8*u(30,32)], // [27,-0.6],
                    [23+u(24,28)+u(34,36),3-u(22,24)-0.8*u(30,32)-1.2*u(34,36)],  // [29,-3],
                    [23+u(24,28)-u(32,34)+u(34,36),3-u(22,24)-0.8*u(30,32)-1.2*u(34,36)], // [27,-3],
                    [23+u(24,28)-u(32,34),3-u(22,24)-0.8*u(30,32)], // [25,-0.6],
                    [23+u(24,28)-u(32,34),3-u(22,24)-0.2*u(30,32)], // [25,0.6],
                    [23+u(24,28),3-u(22,24)-0.2*u(30,32)], // [27,0.6],
                    [23+u(24,28),3-u(22,24)], // [27,1],
                    [23+u(24,26),3-u(22,24)], // [25,1],
                    [23+u(24,26),3-u(22,24)-u(30,34)], // [25,-3],
                    [],
                ],
                T: [
                    [5.5,3-u(0,2)], // [5.5,1],
                    [5.5,3], // [5.5,3],
                    [5.5+0.875*u(2,6),3], // [9,3],
                    [5.5+0.875*u(2,6),3-u(0,2)], // [9,1],
                    [], // 0.875
                ],
                E: [
                    [10,3],
                    [10,3-u(4,6)-u(12,16)], // [10,-3],
                    [10+u(6,8)+u(20,24),3-u(4,6)-u(12,16)], // [16,-3],
                    [10+u(6,8)+u(20,24),3-u(4,6)-u(12,14)], // [16,-1],
                    [10+u(6,8),3-u(4,6)-u(12,14)], // [12,-1],
                    [10+u(6,8),3-u(4,6)-0.8*u(12,14)], // [12,-0.6],
                    [10+u(6,8)+u(16,20),3-u(4,6)-0.8*u(12,14)], // [16,-0.6],
                    [10+u(6,8)+u(16,20),3-u(4,6)-0.2*u(12,14)], // [16,0.6],
                    [10+u(6,8),3-u(4,6)-0.2*u(12,14)], // [12,0.6],
                    [10+u(6,8),3-u(4,6)], // [12,1],
                    [10+u(6,12),3-u(4,6)], // [16,1],
                    [10+u(6,12),3],
                    [],
                ],
                C: [
                    [17,3],
                    [17+u(12,18),3], // [23,3],
                    [17+u(12,18),3-u(10,12)],// [23,1],
                    // [19,1],
                    // [19,-1],
                    // [23,-1],
                    // [23,-3],
                    [17,3-u(10,12)], // [17,-3],
                    [],
                ],
                H: [
                    [24,3],
                    [26,3],
                    [26,0.6],
                    [28,0.6],
                    [28,3],
                    [30,3],
                    [30,-3],
                    [28,-3],
                    [28,-0.6],
                    [26,-0.6],
                    [26,-3],
                    [24,-3],
                    []
                ]
            };
            return [
                /** Back Circle */
                { effect:['silver','mask','shadow'], debug:false, path:[
                    [0,5],
                    [5,5,0,0,0,0,-5],
                    [5,5,0,0,0,0,5],
                ]},
                /** Main Shape */
                { id:'logo', fill:'#FE0000', effect:['shadow'], debug:false, path:[
                    ...'LASOR'.split('').map(c=>S[c].map(x=>x.length?[x[0]-u(0,30)/1.2,-x[1]]:[])).flat(),
                    ...S.L.map(x=>x.length?[-x[0]+u(0,30)/5, x[1]]:[]),
                    ...'TEC'.split('').map(c=>S[c].map(x=>x.length?[x[0]+u(0,30)/5,-x[1]]:[])).flat(),
                ]}
            ]
        },
    });

    /** Grainy texture */
    grainy:string = 'data:image/svg+xml;base64,'+btoa(new TextEncoder().encode
    (xml`
        <svg xmlns="http://www.w3.org/2000/svg" width="500" height="500">
            <filter id="noise" x="0" y="0">
            <feTurbulence type="fractalNoise" baseFrequency="0.65" numOctaves="3" stitchTiles="stitch"/>
            <feBlend in2="SourceGraphic" mode="screen"/>
            </filter>
            <rect width="500" height="500" filter="url(#noise)" opacity="0.5"/>
        </svg>
    `).reduce((acc, byte) => acc + String.fromCharCode(byte), ''));
    
    /** Grainy replacement */
    grainy_new = new Graphics({
        width:500, height:500,
        effects:{noise:[
            {'':'turbulence', type:'fractalNoise', baseFrequency:0.65, numOctaves:3, stitchTiles:'stitch'},
            {'':'blend', in2:'SourceGraphic', mode:'screen'},
        ]},
    }).data;

    /** Style of website *(SCSS)* */
    style:string = /*css*/`
        body {
            background-color: #111;
            &::before {
                content: '';
                position: fixed;
                left: 0;
                top: 0;
                width: 100%;
                height: 100%;
                filter: contrast(170%) brightness(50%);
                opacity: 0.5;
                background-image:url(${this.grainy});
                background-position: 0 0;
                background-repeat: repeat;
                background-size: 300px 300px;background-color:#11111f;
                box-shadow: inset 0 0 ${this.unit}px #1115;
            }
        }
        #logo {
            position: fixed;
            left: 50%;
            top: 50%;
            width: 75%;
            transform: translate(-50%, -50%);
        }
    `;
    
    /** Content of website *(HTML)* */
    content:string = xml`
        <!DOCTYPE html>
        <html>
            <head>
                <title>LasorTech</title>
                <meta charset="utf-8">
                <meta name="viewport" content="width=device-width, inital-scale=1.0">
                <style>${sass(this.style).to_string() as string}</style>
                <svg><defs>${this.logo.defs}</defs></svg>
            </head>
            <body>
                ${this.logo.svg}
                <p>THIS IS JUST A CONCEPT</p>
            </body>
        </html>
    `;

    /** HTTP Server */
    server:Deno.HttpServer<Deno.NetAddr>;
}

/** Main Code */
if (import.meta.main) {
    const _web = new Website();
    //const _tmp = await new Scrapper().start();
}